sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - 'lander --upload --ltd-product lse-429 --pdf LSE-429.pdf --env travis --lsstdoc LSE-429.tex'
env:
  global:
    - secure: "EJx1aKiGw46edYuHzTkoxBfc3uLWF/CbHCgzIlxqs44o3hLn5BFmcuB3e2Sf/ws4yZfqKditMKv9+kz0x+awaPGk8NiL+5lRfj7fNZHfxF5ez8/hoSM+hxLZAKLHiFCrAraOrOmbVnWAeXE5faO2SyPGfhwwlgQJMlQL5QwJaejyMYsr7Oww8vS8FAd+ZevsmpA0KzECzR0MFALEI3kB2UlUbIsJL/rv78Ie2m/EZOVhNd0xA6kKKIqIoT76FLl695oPIKuUAtStFVgL/y6us5ZVlSLZIuUBrxtZ9r4WuKRwn3Ou5n6nd9jwgWtBzc6eswXNDdAIpAv5BLvoL96NJjZWNcAXShnq7ZgLqqelRS2w+kJgefRKpahTv6SM//CQ6M0IUBiIUEeFXOx1e8QUCyao5lvdecAQ5b9BHRn7EGNAN9SJsvBfQTd3IOgS+kznW7jvJBeqLnO7ECunhjdfWbu6J+9deyzPTYKOhOyB1SrkJvMi9hm1NeZkXDVHpr0SFHReU1XVxbEgFPDbR1EJxZChxdtFYB2ZqDA8t7hpxxTt/L3l2IIU2WMbvJmTiuzeikrN8ynNqVOv9tvS4d3SAslAd3CjtQ/BcgiHjBvvW1C2j79/UhoFcNpslKaxArZYyrlKCzHasY563kxp+B5sjFIPQA7xnImliyCUtcO5pbg="
    - secure: "Fd664R2jaBc9Q0I4FACVoRYEQZ/41bG7+DCACJI/EJmXbhK0wXy0QepHhUuJ3kLOQdu0wkJWgFb7arZ5j+YgCpsUpnqtLty1WOd6CNM+R6CBSlNcR1QytRv5wZokgPEFNnsV3ubpBtPT3FJ9tS1aDcd73II4OUqa82ObHmoJfAvuRsCn6++jXchHP3HcYcHJ2ciseGGDCzYvNCg1/aRPghaNuofSIHe8AdhBXQ96LA9UjvyrT4q1lOFivGmWB8j6kmcmGRGNEHOgwejbB3H2ATkuFqgCy0l1xnmc12yHMzSLt1WtY/bB7yAw1ljTNxmR4EsAGKXgyTJ8dVC22+LFTZucxwopwAQ3/E3ioGeCScAtDY2UtVYjeq/3OzgEMFiVYdNc4KB1lxvwlwxusZnKJsz10xG9NniFlmZw1/dLzBIboKeXRvqB03/lmcYVMoCKco+E+8V0cFfHbJUe/7wiUcRWVW0Qot6dclJXJ8ju5OBEDFsd94LGir1P5I9VV+AIl248FYczryIus7RbmiryrRh/qAth6ZTLTxpLn0/ca31yuI4/PIEefKv+1Ymnfz8hT4mgcU8zWDaHUpSCkXXPjft+511IOuMWGlplVxZpuS0iOkg4Or1layl6wX/ein+xALsgB2KAZLGV/dS6GbYsZx/aMvTsnkzAMmwST24T4Pk="
